apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deployment
  namespace: rafi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
      - name: springboot-container
        image: rafi345/springboot-app:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-service
  namespace: rafi
spec:
  selector:
    app: springboot-app
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001
